### ISSUE TITLE
could not compile `bevy_dylib`

### ISSUE THREAD

**Issue by dromer** [tomara-x/quartz#97]
Saw your project and wanted to try a build. Linux and rust 1.76.0

```
   Compiling bevy_dylib v0.13.0
error: the linked panic runtime `panic_unwind` is not compiled with this crate's panic strategy `abort`

error: could not compile `bevy_dylib` (lib) due to 1 previous error
```

**Comment by tomara-x** [comment]
oh lol sorry release is still untested, you should comment out dynamic linking if you want to build release
https://github.com/tomara-x/quartz/blob/main/Cargo.toml#L37

**Comment by tomara-x** [comment]
also maybe comment out the lto, i haven't tested how that works, and it *can* take a ridiculous amount of time to compile 
https://github.com/tomara-x/quartz/blob/main/Cargo.toml#L60

**Comment by dromer** [comment]
The compile is ok, it's the linker stage that takes long ;)

**Comment by dromer** [comment]
Ok, without dynamic linking and lto, no `--release`:

```rust
$ RUST_BACKTRACE=1 cargo run 
    Finished dev [optimized + debuginfo] target(s) in 0.12s
     Running `target/debug/quartz`
2024-03-03T03:50:02.515763Z  INFO bevy_winit::system: Creating new window "awawawa" (0v1)
2024-03-03T03:50:02.515888Z  INFO log: Guessed window scale factor: 1.0833333333333333    
2024-03-03T03:50:02.595043Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 2060", vendor: 4318, device: 7944, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "525.147.05", backend: Vulkan }
thread 'main' panicked at /home/dreamer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.13.0/src/renderer/mod.rs:289:10:
called `Result::unwrap()` on an `Err` value: RequestDeviceError { inner: Core(DeviceLost) }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
   3: futures_lite::future::block_on
   4: <bevy_render::RenderPlugin as bevy_app::plugin::Plugin>::build
   5: bevy_app::app::App::add_boxed_plugin
   6: bevy_app::plugin_group::PluginGroupBuilder::finish
   7: <P as bevy_app::plugin::sealed::Plugins<bevy_app::plugin::sealed::PluginGroupMarker>>::add_to_app
             at /home/dreamer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.13.0/src/plugin.rs:147:13
   8: bevy_app::app::App::add_plugins
             at /home/dreamer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.13.0/src/app.rs:756:9
   9: quartz::main
             at ./src/main.rs:32:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by tomara-x** [comment]
yeah, the linker is generally slow, you should try the mold linker if you want quicker linking:
https://bevyengine.org/learn/quick-start/getting-started/setup/#enable-fast-compiles-optional

i've disabled dynamic_linkine in b2ed28a i should get in the habit of using the command line feature anyways

i have no idea why bevy_render is panicking for you..

**Comment by tomara-x** [comment]
you could try cloning bevy and running one of the 2d examples and see if you get the same panic, if so report an issue there

**Comment by tomara-x** [comment]
or.. wait a minute! i think you need to install the dependencies of bevy first
https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md

i should probably mention that in the instructions

**Comment by dromer** [comment]
Ah! Apparently I needed to install `libnvidia-rtcore` package!

**Comment by dromer** [comment]
It does a thing: 

![](https://i.imgur.com/dkgxXvp.png)
